name: sf-fwa
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  - numpy
  - pandas
  - tqdm
  - Cython
  - pip:
    - cec2013lsgo
    - gym
    - mujoco